version: "3"

tasks:
  start:
    cmds:
      - go run server.go
  tailwind:
    cmds:
      - ./tailwindcss -i static/input.css -o static/output.css --watch
  tailwind-build:
    cmd:
      - ./tailwindcss -i input.css -o output.css --minify
